server:
  port: 9321
spring:
  application:
    name: datamodel-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://124.70.31.149:20303/eureka/
#      defaultZone: http://euk1.com:7001/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
