server:
  port: 9062
spring:
  application:
    name: oneservice-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

